#use node_js
language: node_js

cache:
  bundler: true
  directories:
  - node_modules # NPM packages
  - .jekyll-cache # NPM packages

#define node js version to use
node_js:
  - 14

#choose branch on commit of which this script should excecute
branches:
  only:
    - master
    - beta

#set notifications frequency
notifications:
  email:
    on_success: never
    on_failure : change


before_install:
  #install rvm 2.3
  - rvm install 2.4
  #use rvm 2.3
  - rvm use 2.4
  #install gems through bundler
  - gem install bundler
  #if gems are missing this script will get the missing gems.
  - bundle check || bundle install

install:
  #install firebase tools, required to deploy on firebase hosting
  - npm -g i firebase-tools


# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  #continue even after error
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then JEKYLL_ENV=production jekyll build ; fi
  - if [ "$TRAVIS_BRANCH" == "beta" ]; then jekyll build --config _config.yml,_config.beta.yml ; fi

after_success:
  # deploy to firebase using stored token.
  - if [ "$TRAVIS_BRANCH" == "master" ]; then firebase deploy --token "$FIREBASE_TOKEN" --project master ; fi
  - if [ "$TRAVIS_BRANCH" == "beta" ]; then firebase deploy --token "$FIREBASE_TOKEN" --project beta; fi

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

#Visit article at - http://wrapcode.com
#Cheers, Rahul.
