# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
name: NG-DE 2021
title: NG-DE 2021 - Angular Conference - 2021 in Berlin
description: >- # this means to ignore newlines until "baseurl:"
  Angular-Conference - Summer 2021 - Berlin

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ng-de.org" # the base hostname & protocol for your site, e.g. http://example.com
ga_property: "UA-121643275-1"

# Build settings
markdown: kramdown

permalink: /news/:slug/

plugins:
- jekyll-autoprefixer

autoprefixer:
  only_production: true

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Delete the lines you don't need
# about 5 elements are recomended
# github_username:  ngdeconf
facebook_username: ngdeconf
twitter_username: ngdeconf
# medium_username:  ngdeconf
newsletter: https://ng-de.us5.list-manage.com/subscribe?u=465db430c1cb88ec6dea2ca40&id=a64bc22ee3


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "/imgs/angularjs-de-logo.png"


front_img: yes
front_img_path: "/imgs/daniel-brosch-594428-unsplash.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "/assets/favicons/"
#favicon_img_path: "https://external.url/favicon.ico"

feature_flags:
  speaker_enabled: false

defaults:
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      header_image: "header.jpg"